version: '3'
services:
  php-app:
    build: ./app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:  
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=appointmentportal
      - DB_USERNAME=root
      - DB_PASSWORD=test@123
    volumes:
      - ./app:/var/www/html

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test@123
      MYSQL_DATABASE: appointmentportal
      MYSQL_USER: grace
      MYSQL_PASSWORD: grace_65
    ports:
      - "9906:3306" 

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80