version: '3.8'
services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html/
    ports:
      - 8000:80  
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@32
      MYSQL_DATABASE: appointmentPortal 
      MYSQL_USER: grace
      MYSQL_PASSWORD: 4321
    ports:
      - "9906:3306"  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80